### ISSUE TITLE
NTP chrony

### ISSUE THREAD

**Issue by jilgue** [CallePuzzle/ansible-playbook-install-archlinux#5]
https://wiki.archlinux.org/title/Chrony

**Comment by jilgue** [comment]
```yaml
---
- name: Installation base
  hosts: all
  tasks:

    - name: Install chrony
      package:
        name: chrony

    - name: Configure chrony
      copy:
        src: ../files/chrony.conf
        dest: "/etc/chrony.conf"

    - name: Start and enable chrony
      service:
        name: chronyd
        state: started
        enabled: true

    - name: Install tlp
      package:
        name: tlp

    - name: Start and enable tlp
      service:
        name: tlp
        state: started
        enabled: true
# https://wiki.archlinux.org/index.php/Bumblebee

```
